{"CVE Code": "CVE-2025-4517", "Description": "Allows arbitrary filesystem writes outside the extraction directory during extraction with filter=\"data\".\n\n\nYou are affected by this vulnerability if using the tarfile\u00a0module to extract untrusted tar archives using TarFile.extractall()\u00a0or TarFile.extract()\u00a0using the filter=\u00a0parameter with a value of \"data\"\u00a0or \"tar\". See the tarfile  extraction filters documentation https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter \u00a0for more information.\n\nNote that for Python 3.14 or later the default value of filter=\u00a0changed from \"no filtering\" to `\"data\", so if you are relying on this new default behavior then your usage is also affected.\n\nNote that none of these vulnerabilities significantly affect the installation of source distributions which are tar archives as source distributions already allow arbitrary code execution during the build process. However when evaluating source distributions it's important to avoid installing source distributions with suspicious links.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2025-4517", "Vulnerability Categories": "N/A", "Affected Products": "N/A", "EPSS Score": "0.07% Probability of exploitation activity in the next 30 days\n~ 23 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n Could not find any EPSS score change records for this CVE ", "CVSS Scores": "9.4", "CWE": [{"CWE_ID": "CWE-22 Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')", "CWE_link": "/cwe-details/22/Improper-Limitation-of-a-Pathname-to-a-Restricted-Directory-.html"}], "Reference": [{"ref_link": "https://github.com/python/cpython/pull/135037", "ref_desc": "CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/6pBSMIh5UkRAX80F6Q85oSvEnY4.html"}, {"ref_link": "https://github.com/python/cpython/commit/4633f3f497b1ff70e4a35b6fe2c907cbe2d4cb2e", "ref_desc": "CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/7lxTyMS9nDh6y5bah0Msn-8ZK0Q.html"}, {"ref_link": "https://github.com/python/cpython/commit/aa9eb5f757ceff461e6e996f12c89e5d9b583b01", "ref_desc": "[3.13] gh-135034: Normalize link targets in tarfile, add `os.path.rea\u2026 \u00b7 python/cpython@aa9eb5f \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/CSA1R0v7b8oLY4L3pxczGg9iPKk.html"}, {"ref_link": "https://github.com/python/cpython/commit/19de092debb3d7e832e5672cc2f7b788d35951da", "ref_desc": "CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/Du0AbbKEDcX6dQbNCEjDrsL-s7s.html"}, {"ref_link": "https://github.com/python/cpython/commit/3612d8f51741b11f36f8fb0494d79086bac9390a", "ref_desc": "gh-135034: Normalize link targets in tarfile, add `os.path.realpath(s\u2026 \u00b7 python/cpython@3612d8f \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/FUj6yIO92Q3VZ2ByXhDRjL56YEw.html"}, {"ref_link": "https://github.com/python/cpython/commit/28463dba112af719df1e8b0391c46787ad756dd9", "ref_desc": "[3.12] gh-135034: Remove test_realpath_permission (GH-135093) \u00b7 python/cpython@28463db \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/hKlG0kpcSj1cEsa67ePufO3zM0E.html"}, {"ref_link": "https://github.com/python/cpython/commit/9c1110ef6652687d7c55f590f909720eddde965a", "ref_desc": "[3.10] gh-135034: Normalize link targets in tarfile, add `os.path.rea\u2026 \u00b7 python/cpython@9c1110e \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/nP5kJW8hdZi1lm_3BC3oJICLlCk.html"}, {"ref_link": "https://gist.github.com/sethmlarson/52398e33eff261329a0180ac1d54f42f", "ref_desc": "Mitigation for CVE-2025-4517, CVE-2025-4330, CVE-2025-4138, and CVE-2024-12718 \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/nS2gAC55EU67dzCiu6Im-UWkb3A.html"}, {"ref_link": "https://github.com/python/cpython/commit/9e0ac76d96cf80b49055f6d6b9a6763fb9215c2a", "ref_desc": "CVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/qN0YzEnHptjtuRDvkg7WvjAPfc4.html"}, {"ref_link": "https://github.com/python/cpython/issues/135034", "ref_desc": "(TODO) Empty tracking issue \u00b7 Issue #135034 \u00b7 python/cpythonCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/VliAfan6PFzFIIu2wwOp4EdaiUQ.html"}, {"ref_link": "https://mail.python.org/archives/list/security-announce@python.org/thread/MAXIJJCUUMCL7ATZNDVEGGHUMQMUUKLG/", "ref_desc": "Mailman 3 Multiple CVEs (1 CRITICAL, 3 HIGH, 1 MODERATE) affecting the tarfile module - Security-announce - python.orgCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/WeS98IHdXp0dRPhjfQpHz_31hfQ.html"}, {"ref_link": "https://github.com/python/cpython/commit/dd8f187d0746da151e0025c51680979ac5b4cfb1", "ref_desc": "[3.9] gh-135034: Normalize link targets in tarfile, add `os.path.real\u2026 \u00b7 python/cpython@dd8f187 \u00b7 GitHubCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/XQB8gnPZY8VkzsILuoB61Kmwnj0.html"}]}