{"CVE Code": "CVE-2023-49080", "Description": "The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila. Unhandled errors in API requests coming from an authenticated user include traceback information, which can include path information. There is no known mechanism by which to trigger these errors without authentication, so the paths revealed are not considered particularly sensitive, given that the requesting user has arbitrary execution permissions already in the same environment. A fix has been introduced in commit `0056c3aa52` which no longer includes traceback information in JSON error responses. For compatibility, the traceback field is present, but always empty. This commit has been included in version 2.11.2. Users are advised to upgrade. There are no known workarounds for this vulnerability.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2023-49080", "Vulnerability Categories": "N/A", "Affected Products": "\nJupyter\u00bbJupyter ServerVersions  before (<) 2.11.2cpe:2.3:a:jupyter:jupyter_server:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.10% Probability of exploitation activity in the next 30 days\n~ 42 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-11-03  0.08%  0.10%  +0.01 \n 2  2024-10-23  0.08%  0.08%  +0.01 \n 3  2024-09-17  0.06%  0.08%  +0.02 \n 4  2023-12-14  0.05%  0.06%  +0.01 \n 5  2023-12-08  0.05%  0.05%  +0.01 ", "CVSS Scores": "4.3", "CWE": [{"CWE_ID": "CWE-209 Generation of Error Message Containing Sensitive Information", "CWE_link": "/cwe-details/209/Generation-of-Error-Message-Containing-Sensitive-Information.html"}], "Reference": [{"ref_link": "https://github.com/jupyter-server/jupyter_server/commit/0056c3aa52cbb28b263a7a609ae5f17618b36652", "ref_desc": "Merge pull request from GHSA-h56g-gq9v-vc8r \u00b7 jupyter-server/jupyter_server@0056c3a \u00b7 GitHubPatch", "ref_cve_link": "N/A"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FG2JWZI5KPUYMDPS53AIFTZJWZD3IT6I/", "ref_desc": "[SECURITY] Fedora 38 Update: python-jupyter-server-2.1.0-3.fc38 - package-announce - Fedora Mailing-Lists", "ref_cve_link": "N/A"}, {"ref_link": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/62LO7PPIAMLIDEKUOORXLHKLGA6QPL77/", "ref_desc": "[SECURITY] Fedora 39 Update: python-jupyter-server-2.7.2-2.fc39 - package-announce - Fedora Mailing-Lists", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-h56g-gq9v-vc8r", "ref_desc": "Server errors include tracebacks with path information \u00b7 Advisory \u00b7 jupyter-server/jupyter_server \u00b7 GitHubThird Party Advisory", "ref_cve_link": "N/A"}]}