{"CVE Code": "CVE-2019-16228", "Description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2019-16228", "Vulnerability Categories": "N/A", "Affected Products": "\nPy-lmdb Project\u00bbPy-lmdbVersions  up to, including, (<=) 0.97cpe:2.3:a:py-lmdb_project:py-lmdb:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.12% Probability of exploitation activity in the next 30 days\n~ 47 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.12%  0.12%  +0.01 \n 2  2023-03-07  0.89%  0.12%  -0.77 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-369 Divide By Zero", "CWE_link": "/cwe-details/369/Divide-By-Zero.html"}], "Reference": [{"ref_link": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE", "ref_desc": "pocs/lmdb/FPE at master \u00b7 TeamSeri0us/pocs \u00b7 GitHubExploit;Third Party Advisory", "ref_cve_link": "N/A"}]}