{"CVE Code": "CVE-2015-3220", "Description": "The tlslite library before 0.4.9 for Python allows remote attackers to trigger a denial of service (runtime exception and process crash).", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2015-3220", "Vulnerability Categories": "Overflow;Denial of service", "Affected Products": "\nTlslite Project\u00bbTlslite\u00bbForPythonVersions  up to, including, (<=) 0.4.9cpe:2.3:a:tlslite_project:tlslite:*:*:*:*:*:python:*:*Matching versions", "EPSS Score": "0.33% Probability of exploitation activity in the next 30 days\n~ 71 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.44%  0.33%  -0.11 \n 2  2023-05-08  0.33%  0.44%  +0.11 \n 3  2023-03-07  1.14%  0.33%  -0.81 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-119 Improper Restriction of Operations within the Bounds of a Memory Buffer", "CWE_link": "/cwe-details/119/Improper-Restriction-of-Operations-within-the-Bounds-of-a-Me.html"}], "Reference": [{"ref_link": "https://groups.google.com/forum/#!topic/tlslite-dev/MoWE7B0A4iU", "ref_desc": "tlslite-0.4.9 - Google Groepen", "ref_cve_link": "N/A"}, {"ref_link": "https://bugzilla.redhat.com/show_bug.cgi?id=1254215", "ref_desc": "1254215 \u2013 (CVE-2015-3220) CVE-2015-3220 python-tlslite: denial of service triggered by a malformed packetIssue Tracking;Third Party Advisory;VDB Entry", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/trevp/tlslite/commit/aca8d4f898b436ff6754e1a9ab96cae976c8a853", "ref_desc": "Fix IndexError on junk message. \u00b7 trevp/tlslite@aca8d4f \u00b7 GitHubPatch;Third Party Advisory", "ref_cve_link": "N/A"}]}