{"CVE Code": "CVE-2025-26699", "Description": "An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13, and 4.2 before 4.2.20. The django.utils.text.wrap() method and wordwrap template filter are subject to a potential denial-of-service attack when used with very long strings.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2025-26699", "Vulnerability Categories": "Denial of service", "Affected Products": "N/A", "EPSS Score": "0.13% Probability of exploitation activity in the next 30 days\n~ 34 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2025-06-04  0.12%  0.13%  +0.01 \n 2  2025-06-01  0.13%  0.12%  -0.01 \n 3  2025-05-13  0.11%  0.13%  +0.02 \n 4  2025-05-04  0.10%  0.11%  +0.01 \n 5  2025-04-30  0.12%  0.10%  -0.02 \n 6  2025-04-15  0.07%  0.12%  +0.05 \n 7  2025-04-07  0.06%  0.07%  +0.01 \n 8  2025-03-30  0.05%  0.06%  +0.01 \n 9  2025-03-29  0.06%  0.05%  -0.01 \n 10  2025-03-20  0.06%  0.06%  +0.00 \n 11  2025-03-17  0.05%  0.06%  +0.01 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-770 Allocation of Resources Without Limits or Throttling", "CWE_link": "/cwe-details/770/Allocation-of-Resources-Without-Limits-or-Throttling.html"}], "Reference": [{"ref_link": "https://groups.google.com/g/django-announce", "ref_desc": "django-announce - Google GroupsCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/7Kv1mhz3CyWuc-iy_G2zgXiEkSU.html"}, {"ref_link": "https://www.djangoproject.com/weblog/2025/mar/06/security-releases/", "ref_desc": "Django security releases issued: 5.1.7, 5.0.13 and 4.2.20 | Weblog | Django", "ref_cve_link": "N/A"}, {"ref_link": "https://docs.djangoproject.com/en/dev/releases/security/", "ref_desc": "Archive of security issues | Django documentation | DjangoCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/InwfdzuHdb1agC8uMwH31EJtlGA.html"}, {"ref_link": "http://www.openwall.com/lists/oss-security/2025/03/06/12", "ref_desc": "oss-security - CVE-2025-26699: Django: Potential denial-of-service in django.utils.text.wrap()", "ref_cve_link": "N/A"}, {"ref_link": "https://lists.debian.org/debian-lts-announce/2025/03/msg00012.html", "ref_desc": "", "ref_cve_link": "N/A"}]}