{"CVE Code": "CVE-2022-44079", "Description": "pycdc commit 44a730f3a889503014fec94ae6e62d8401cb75e5 was discovered to contain a stack overflow via the component __sanitizer::StackDepotBase<__sanitizer::StackDepotNode.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2022-44079", "Vulnerability Categories": "Memory Corruption", "Affected Products": "\nPycdc Project\u00bbPycdc\u00bbVersion:2022-10-04cpe:2.3:a:pycdc_project:pycdc:2022-10-04:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.07% Probability of exploitation activity in the next 30 days\n~ 30 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-05-23  0.05%  0.07%  +0.02 \n 2  2024-04-12  0.04%  0.05%  +0.01 \n 3  2023-03-07  0.89%  0.04%  -0.84 ", "CVSS Scores": "5.5", "CWE": [{"CWE_ID": "CWE-787 Out-of-bounds Write", "CWE_link": "/cwe-details/787/Out-of-bounds-Write.html"}], "Reference": [{"ref_link": "https://github.com/zrax/pycdc/issues/291", "ref_desc": "Stack-overflow occurred in operator new(unsigned long) of pyc_object.cpp. \u00b7 Issue #291 \u00b7 zrax/pycdc \u00b7 GitHubExploit;Issue Tracking;Third Party Advisory", "ref_cve_link": "N/A"}]}