{"CVE Code": "CVE-2022-23586", "Description": "Tensorflow is an Open Source Machine Learning Framework. A malicious user can cause a denial of service by altering a `SavedModel` such that assertions in `function.cc` would be falsified and crash the Python interpreter. The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2022-23586", "Vulnerability Categories": "Denial of service", "Affected Products": "\nGoogle\u00bbTensorflowVersions  up to, including, (<=) 2.5.2cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflowVersions  from including (>=) 2.6.0andup to, including, (<=) 2.6.2cpe:2.3:a:google:tensorflow:*:*:*:*:*:*:*:*Matching versions\nGoogle\u00bbTensorflow\u00bbVersion:2.7.0cpe:2.3:a:google:tensorflow:2.7.0:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.17% Probability of exploitation activity in the next 30 days\n~ 54 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.32%  0.17%  -0.15 \n 2  2024-10-07  0.22%  0.32%  +0.10 \n 3  2024-04-28  0.17%  0.22%  +0.05 \n 4  2023-09-26  0.14%  0.17%  +0.03 \n 5  2023-09-12  0.12%  0.14%  +0.03 \n 6  2023-08-28  0.10%  0.12%  +0.02 \n 7  2023-03-07  0.95%  0.10%  -0.85 ", "CVSS Scores": "4.0", "CWE": [{"CWE_ID": "CWE-617 Reachable Assertion", "CWE_link": "/cwe-details/617/Reachable-Assertion.html"}], "Reference": [{"ref_link": "https://github.com/tensorflow/tensorflow/commit/3d89911481ba6ebe8c88c1c0b595412121e6c645", "ref_desc": "Eliminate `CHECK`-fail from `function.cc`. \u00b7 tensorflow/tensorflow@3d89911 \u00b7 GitHubPatch;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/tensorflow/tensorflow/commit/dcc21c7bc972b10b6fb95c2fb0f4ab5a59680ec2", "ref_desc": "Eliminate debug `CHECK`-fail from `function.cc` \u00b7 tensorflow/tensorflow@dcc21c7 \u00b7 GitHubPatch;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/tensorflow/tensorflow/blob/a1320ec1eac186da1d03f033109191f715b2b130/tensorflow/core/framework/function.cc", "ref_desc": "tensorflow/function.cc at a1320ec1eac186da1d03f033109191f715b2b130 \u00b7 tensorflow/tensorflow \u00b7 GitHubExploit;Third Party Advisory", "ref_cve_link": "N/A"}, {"ref_link": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-43jf-985q-588j", "ref_desc": "Multiple `CHECK`-fails in `function.cc` \u00b7 Advisory \u00b7 tensorflow/tensorflow \u00b7 GitHubPatch;Third Party Advisory", "ref_cve_link": "N/A"}]}