{"CVE Code": "CVE-2019-14958", "Description": "JetBrains PyCharm before 2019.2 was allocating a buffer of unknown size for one of the connection processes. In a very specific situation, it could lead to a remote invocation of an OOM error message because of Uncontrolled Memory Allocation.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2019-14958", "Vulnerability Categories": "N/A", "Affected Products": "\nJetbrains\u00bbPycharmVersions  before (<) 2019.2cpe:2.3:a:jetbrains:pycharm:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.10% Probability of exploitation activity in the next 30 days\n~ 41 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2023-03-07  0.89%  0.10%  -0.78 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-770 Allocation of Resources Without Limits or Throttling", "CWE_link": "/cwe-details/770/Allocation-of-Resources-Without-Limits-or-Throttling.html"}], "Reference": [{"ref_link": "https://blog.jetbrains.com/blog/2019/09/26/jetbrains-security-bulletin-q2-2019/", "ref_desc": "JetBrains Security Bulletin Q2 2019 | JetBrains BlogVendor AdvisoryCVEs referencing this url", "ref_cve_link": "https://www.cvedetails.com/reference-url-info/key0k4YEn2AH9lyhReogpvoH8Hk.html"}]}