{"CVE Code": "CVE-2018-18385", "Description": "Asciidoctor in versions < 1.5.8 allows remote attackers to cause a denial of service (infinite loop). The loop was caused by the fact that Parser.next_block was not exhausting all the lines in the reader as the while loop expected it would. This was happening because the regular expression that detects any list was not agreeing with the regular expression that detects a specific list type. So the line kept getting pushed back onto the reader, hence causing the loop.", "NVD Link": "https://nvd.nist.gov/vuln/detail/CVE-2018-18385", "Vulnerability Categories": "Denial of service", "Affected Products": "\nAsciidoctor\u00bbAsciidoctorVersions  before (<) 1.5.8cpe:2.3:a:asciidoctor:asciidoctor:*:*:*:*:*:*:*:*Matching versions", "EPSS Score": "0.21% Probability of exploitation activity in the next 30 days\n~ 58 % Percentile, the proportion of vulnerabilities that are scored at or less", "EPSS History": "\n #  Date  Old EPSS Score  New EPSS Score  Delta (New - Old) \n 1  2024-12-17  0.29%  0.21%  -0.08 \n 2  2024-08-25  0.27%  0.29%  +0.02 \n 3  2024-07-31  0.26%  0.27%  +0.01 \n 4  2024-06-04  0.25%  0.26%  +0.02 \n 5  2023-07-08  0.30%  0.25%  -0.05 \n 6  2023-03-07  1.06%  0.30%  -0.75 ", "CVSS Scores": "5.0", "CWE": [{"CWE_ID": "CWE-835 Loop with Unreachable Exit Condition ('Infinite Loop')", "CWE_link": "/cwe-details/835/Loop-with-Unreachable-Exit-Condition-Infinite-Loop-.html"}], "Reference": [{"ref_link": "https://github.com/asciidoctor/asciidoctor/issues/2888", "ref_desc": "Infinite loop in Parser#next_block \u00b7 Issue #2888 \u00b7 asciidoctor/asciidoctor \u00b7 GitHubExploit;Third Party Advisory", "ref_cve_link": "N/A"}]}